server:
  port: 9090
 
app:
  environment: Localhost
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personservice?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: personappuser
    password: personappuser
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 25
      pool-name: personservicepool
      auto-commit: false 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        
     
    
    

